import { RPC, TABLES } from "../../utils/config";

export const SESSION_ROUTES = {
  TABLE: TABLES.PARKING_SESSIONS,
  RPC_HANDLE_SCAN: RPC.HANDLE_QR_SCAN,
  RPC_START: RPC.START_PARKING_SESSION,
  RPC_END: RPC.END_PARKING_SESSION,
};
